import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector } from "react-redux";

const Dashboard = () => {
  const { user } = useSelector((store: any) => store.user);
  const { push } = useRouter();
  useEffect(() => {
    if (!user) {
      push("/");
    }
  }, [user]);
  return (
    <>
      <Head>
        <title>Charity Org</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/charityApp.png" />
      </Head>
      {user && (
        <main>
          Welcome, {user?.user?.firstName} {user?.user?.lastName}
        </main>
      )}
    </>
  );
};
export default Dashboard;
