import Head from "next/head";
import { Inter } from "next/font/google";
import Login from "../components/auth/login";
import Register from "@/components/auth/register";
import ParticlesComp from "@/components/ParticlesComp";
import styles2 from "../components/auth/auth.module.css";
import { useState } from "react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isLogin, setIsLogin] = useState(true);
  return (
    <>
      <Head>
        <title>Charity Org</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles2.container}>
        <nav className={styles2.nav}>
          <div className={styles2.logo}>Logo</div>
          <ul className={styles2.menu}>
            <li>Wallet</li>
            <li>Course</li>
            <li>Theme</li>
          </ul>
        </nav>
        <div className={styles2.section}>
          <div className={styles2.left}>
            <h1>Welcome to charity.org</h1>
            <h3>be a part of something profound</h3>
            <h3>donate to a worthy course</h3>
          </div>
          <div className={styles2.right}>
            {isLogin && <Login isLogin={isLogin} setIsLogin={setIsLogin} />}
            {!isLogin && <Register isLogin={isLogin} setIsLogin={setIsLogin} />}
          </div>
        </div>
      </main>
      <div className={styles2.particles}>
        <ParticlesComp />
      </div>
    </>
  );
}
